
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: hazard-assimilator
  namespace: streaming
spec:
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: default
  podTemplate: {}
  jobManager:
    replicas: 1
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "4096m"
      cpu: 2
  job:
    jarURI: local:///opt/flink/usrlib/hazard-assim.jar
    parallelism: 2
    upgradeMode: stateless
    args: ["--input.topic=hazard_tiles", "--output.topic=nowcast_tiles"]
