
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: exposure
      POSTGRES_USER: exposure
      POSTGRES_PASSWORD: exposure
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://exposure:exposure@db:5432/exposure
      JWT_SECRET: dev-secret
      S3_BUCKET: exposure-exports
      S3_ENDPOINT_URL: ""
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      CORS_ORIGINS: http://localhost:5173
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE: http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
